services:
    aspone.services.deposit:
        class: InterInvest\AsponeBundle\Services\AsponeDeposit
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@besimple.soap.client.builder.teledeclarations"]
    aspone.services.monitoring:
        class: InterInvest\AsponeBundle\Services\AsponeMonitoring
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    aspone.services.xml:
        class: InterInvest\AsponeBundle\Services\AsponeXml
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
    aspone.services.pdf:
        class: InterInvest\AsponeBundle\Services\AsponePdf
        arguments: ["@service_container", "@aspone.services.xml"]
    aspone.services.declaration:
        class: InterInvest\AsponeBundle\Services\AsponeDeclarationService



    aspone.services.formulaire:
        class: InterInvest\AsponeBundle\Services\Formulaire
        arguments: ["@aspone.services.dictionnaire"]

    aspone.services.dictionnaire:
        class: InterInvest\AsponeBundle\Services\Dictionnaire
    aspone.services.soap:
        class: InterInvest\AsponeBundle\Services\Soap
    aspone.services.mydeposit:
        class: InterInvest\AsponeBundle\Services\_Deposit
        arguments: ["@doctrine.orm.entity_manager", "@aspone.services.formulaire"]